### ISSUE TITLE
Enhancement: /broadcast

### ISSUE THREAD

**Issue by jiriks74** [John-Paul-R/Essential-Commands#189]
Add a command to broadcast messages to all players as if sent from server console.

**Comment by John-Paul-R** [comment]
Isn't this what `/tellraw` does?

**Comment by jiriks74** [comment]
> Isn't this what `/tellraw` does?

Well, it *can* do what I want but it requires json syntax. It really isn't suited for quickly sending a server message. The only way to use `/tellraw`, at least for me, it to use something like [this](https://minecraft.tools/en/tellraw.php) to generate the messages for me.

I think that just quickly sending something with just `/broadcast <message>` is way easier than `/tellraw @a {"text":"<message>"}`.

**Comment by John-Paul-R** [comment]
Ah, I understand, that's fair.

I'd frankly recommend just tossing together a shortcut with Command Aliases for something like this. example, for broadcast:

```toml
schemaVersion = 1 # Required | Schema Version
commandMode = "COMMAND_CUSTOM" # Required | Custom Command Format
command = "broadcast" # Required | Parent command name
permission = 4 # Optional | Default: 0 | If LuckPerms is not installed will fallback to these permission level

[[children]] # Optional | List of sub-child commands

child = "message_body"
type = "argument"
argumentType = "minecraft:greedy_string"

[[children.actions]] # Optional | List of actions

command = "tellraw @a {\"text\": \"[Server] {{message_body}}\"}" # Optional | Command to execute will be processed to map variables and process functions
commandType = "SERVER" # Optional | Required if command is present
message = "Broadcasted message." # Optional | Executor gets a local message

```

output:

![broadcast-commandaliases-demo](https://user-images.githubusercontent.com/29154459/223293145-01c9f669-f044-45aa-9fbc-8729dfb2fc2a.gif)
